runtime: python
runtime_config:
  python_version: 3
api_version: 1
threadsafe: yes

entrypoint: gunicorn -b :$PORT occurrence_book.wsgi:application

env: flex

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: occurrence_book.wsgi.application

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$