# Generated by Django 2.0 on 2018-01-16 07:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_o_name', models.CharField(max_length=100)),
                ('a_o_badge_no', models.IntegerField()),
                ('crime_description', models.TextField()),
                ('time', models.TimeField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_no', models.IntegerField(null=True)),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='criminal profile pictures/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_no', models.IntegerField(null=True)),
                ('rank', models.TextField(max_length=50)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('sign', models.CharField(blank=True, max_length=100)),
                ('booking', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ob_system.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_no', models.IntegerField()),
                ('ref_no', models.CharField(blank=True, max_length=150)),
                ('case_file_no', models.CharField(blank=True, max_length=150)),
                ('crime_description', models.TextField()),
                ('time', models.TimeField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.Crime')),
            ],
        ),
        migrations.CreateModel(
            name='UserFullName',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='remark',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ob_system.Report'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occurrencebook',
            name='reports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.Report'),
        ),
        migrations.AddField(
            model_name='booking',
            name='crime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.Crime'),
        ),
        migrations.AddField(
            model_name='booking',
            name='criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.CriminalProfile'),
        ),
    ]
