# Generated by Django 2.0 on 2018-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badge_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
