# Generated by Django 2.0 on 2018-01-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ob_system.Booking'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ob_system.Report'),
        ),
    ]
