# Generated by Django 2.0 on 2018-01-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='criminal',
        ),
        migrations.RemoveField(
            model_name='occurrencebook',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='occurrencebook',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='crime',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Crime',
        ),
        migrations.DeleteModel(
            name='CriminalProfile',
        ),
        migrations.DeleteModel(
            name='OccurrenceBook',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
