# Generated by Django 2.0 on 2018-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0002_auto_20180118_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='criminal profile pictures/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
