# Generated by Django 2.0 on 2018-01-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0002_auto_20180116_1610'),
        ('ob_system', '0002_archive'),
    ]

    operations = [
    ]
