# Generated by Django 2.0 on 2018-01-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0003_merge_20180116_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_station', models.CharField(max_length=250)),
                ('sum', models.IntegerField()),
                ('court_name', models.CharField(max_length=250)),
                ('court_date', models.DateField()),
                ('court_time', models.TimeField()),
                ('current_date', models.DateField()),
                ('current_time', models.TimeField()),
            ],
        ),
    ]
