# Generated by Django 2.0 on 2018-01-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_o_name', models.CharField(max_length=100)),
                ('a_o_badge_no', models.IntegerField()),
                ('crime_description', models.TextField()),
                ('time', models.TimeField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.Crime')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.CriminalProfile')),
            ],
        ),
    ]
