# Generated by Django 2.0 on 2018-01-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0008_occurrencebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.Booking')),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.Report')),
            ],
        ),
    ]
