# Generated by Django 2.0 on 2018-01-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ob_system', '0009_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_station', models.CharField(max_length=250)),
                ('sum', models.IntegerField()),
                ('court_name', models.CharField(max_length=250)),
                ('court_date', models.DateField()),
                ('court_time', models.TimeField()),
                ('current_date', models.DateField()),
                ('current_time', models.TimeField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.Crime')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_system.CriminalProfile')),
            ],
        ),
    ]
